"""
ContextIQ - Parent/Child Retrieval Test Suite
Comprehensive tests verifying parent section chunking, deterministic IDs,
parent context resolution, deduplication, strongest child relevance preservation,
graceful legacy fallback, pipeline integration, and backward compatibility.
All tests use deterministic mocks; zero real Gemini API calls.
"""

from dataclasses import replace
from typing import Any, Dict, List, Optional
from unittest.mock import MagicMock

import pytest

from app.ingestion.chunker import DocumentChunk, TextChunker
from app.ingestion.parent_chunker import ParentChunk, ParentChildChunker
from app.ingestion.pdf_loader import DocumentPage
from app.rag.conversation import ChatMessage, Conversation
from app.rag.pipeline import RAGPipeline, RAGResponse
from app.retrieval.models import RetrievalResult, RetrievedChunk
from app.retrieval.parent_context import resolve_parent_context
from app.retrieval.reranker import TFIDFReranker


# ---------------------------------------------------------------------------
# Test Helpers & Fixtures
# ---------------------------------------------------------------------------

class MockRetriever:
    """Mock retriever returning predetermined child chunks."""
    def __init__(self, chunks: Optional[List[RetrievedChunk]] = None):
        self.chunks = chunks or []
        self.default_top_k = 5
        self.default_min_similarity = 0.50
        self.default_retrieval_mode = "semantic"
        self.vector_store = None

    def retrieve(self, **kwargs) -> List[RetrievedChunk]:
        top_k = kwargs.get("top_k", self.default_top_k)
        thresh = kwargs.get("similarity_threshold", self.default_min_similarity)
        doc_ids = kwargs.get("document_ids")

        filtered = self.chunks
        if doc_ids:
            filtered = [c for c in filtered if c.document_id in doc_ids]
        if thresh is not None:
            filtered = [
                c for c in filtered
                if c.cosine_similarity is None or c.cosine_similarity >= thresh
            ]
        return filtered[:top_k]


class MockGenerator:
    """Mock generator that records the chunks passed to generate()."""
    def __init__(self):
        self.last_retrieved_chunks = []
        self.last_question = None

    def generate(self, question: str, retrieved_chunks: List[RetrievedChunk]) -> str:
        self.last_question = question
        self.last_retrieved_chunks = retrieved_chunks
        return f"Grounded answer based on {len(retrieved_chunks)} context(s)."


# ---------------------------------------------------------------------------
# Tests 1-6: Parent Construction, IDs, and Hierarchical Chunking
# ---------------------------------------------------------------------------

def test_parent_chunk_creation_and_validation():
    """1. ParentChunk creates valid objects and enforces invariant validation."""
    parent = ParentChunk(
        parent_id="doc1_p1_parent0",
        text="This is a full parent section.",
        source="doc1.pdf",
        page_number=1,
        parent_index=0,
        document_id="doc1",
    )
    assert parent.parent_id == "doc1_p1_parent0"
    assert parent.text == "This is a full parent section."
    assert parent.page_number == 1
    assert parent.parent_index == 0
    assert parent.document_id == "doc1"

    # Invariant checks
    with pytest.raises(ValueError):
        ParentChunk(parent_id="", text="Text", source="doc.pdf", page_number=1, parent_index=0)
    with pytest.raises(ValueError):
        ParentChunk(parent_id="p0", text="", source="doc.pdf", page_number=1, parent_index=0)
    with pytest.raises(ValueError):
        ParentChunk(parent_id="p0", text="Text", source="doc.pdf", page_number=0, parent_index=0)
    with pytest.raises(ValueError):
        ParentChunk(parent_id="p0", text="Text", source="doc.pdf", page_number=1, parent_index=-1)


def test_deterministic_parent_id_generation():
    """2. generate_parent_id produces deterministic identifiers with and without document_id."""
    # With document_id
    id1 = ParentChildChunker.generate_parent_id("Quarterly Report.pdf", 2, 0, document_id="abc123hash")
    id2 = ParentChildChunker.generate_parent_id("Quarterly Report.pdf", 2, 0, document_id="abc123hash")
    assert id1 == "abc123hash_p2_parent0"
    assert id1 == id2

    # Without document_id (falls back to sanitized stem)
    id3 = ParentChildChunker.generate_parent_id("Annual Report (Final!).pdf", 1, 3)
    assert id3 == "Annual_Report__Final___p1_parent3"


def test_child_parent_relationship():
    """3. Child chunks generated by ParentChildChunker reference their parent_id and parent_index."""
    chunker = ParentChildChunker(
        parent_chunk_size=1000,
        parent_chunk_overlap=100,
        child_chunk_size=300,
        child_chunk_overlap=50,
    )
    sample_text = "Sentence alpha. " * 50  # ~800 chars, fits in 1 parent
    page = DocumentPage(text=sample_text, page_number=1, source="doc.pdf")

    parents, children = chunker.split_page(page, document_id="doc42")
    assert len(parents) == 1
    assert len(children) > 1

    parent = parents[0]
    assert parent.parent_id == "doc42_p1_parent0"
    for child in children:
        assert child.parent_id == parent.parent_id
        assert child.parent_index == parent.parent_index
        assert child.document_id == "doc42"
        assert child.page_number == 1


def test_metadata_preservation_on_child_chunks():
    """4. Child chunks retain all standard DocumentChunk metadata fields."""
    chunker = ParentChildChunker(
        parent_chunk_size=800,
        parent_chunk_overlap=100,
        child_chunk_size=200,
        child_chunk_overlap=50,
    )
    page = DocumentPage(text="Important contract terms. " * 30, page_number=3, source="contract.pdf")
    parents, children = chunker.split_page(page, document_id="contract_hash")

    assert len(children) >= 2
    for idx, c in enumerate(children):
        assert c.chunk_id == f"contract_hash_p3_c{idx}"
        assert c.source == "contract.pdf"
        assert c.page_number == 3
        assert c.chunk_index == idx
        assert c.document_id == "contract_hash"
        assert c.parent_id == "contract_hash_p3_parent0"


def test_multiple_children_sharing_a_parent():
    """5. When text is large, multiple child chunks are grouped under the same parent section."""
    chunker = ParentChildChunker(
        parent_chunk_size=600,
        parent_chunk_overlap=100,
        child_chunk_size=200,
        child_chunk_overlap=50,
    )
    page = DocumentPage(text="Section paragraph content. " * 60, page_number=1, source="doc.pdf")
    parents, children = chunker.split_page(page, document_id="test_doc")

    assert len(parents) >= 2
    parent_ids = {p.parent_id for p in parents}
    child_parent_ids = {c.parent_id for c in children}
    assert child_parent_ids.issubset(parent_ids)

    # Check that at least one parent has multiple children
    parent0_children = [c for c in children if c.parent_id == parents[0].parent_id]
    assert len(parent0_children) > 1


def test_empty_and_whitespace_page_handling():
    """6. Empty or whitespace pages produce empty lists without error."""
    chunker = ParentChildChunker()
    p_empty = DocumentPage(text="", page_number=1, source="empty.pdf")
    p_white = DocumentPage(text="   \n\t  ", page_number=2, source="empty.pdf")

    parents1, children1 = chunker.split_page(p_empty)
    assert parents1 == [] and children1 == []

    parents2, children2 = chunker.split_page(p_white)
    assert parents2 == [] and children2 == []


# ---------------------------------------------------------------------------
# Tests 7-13: Parent Context Resolver & Deduplication
# ---------------------------------------------------------------------------

def test_duplicate_parent_elimination():
    """7. Multiple child chunks belonging to the same parent are merged into a single parent context."""
    parent_store = {
        "parent_1": {
            "parent_id": "parent_1",
            "text": "Full parent section 1 text spanning both child A and B.",
            "source": "doc1.pdf",
            "page_number": 1,
            "document_id": "doc1",
        },
        "parent_2": {
            "parent_id": "parent_2",
            "text": "Full parent section 2 text for child C.",
            "source": "doc1.pdf",
            "page_number": 2,
            "document_id": "doc1",
        },
    }

    # Child A and Child B both point to parent_1; Child C points to parent_2
    child_a = RetrievedChunk(
        chunk_id="c_a",
        text="child text a",
        source="doc1.pdf",
        page_number=1,
        chunk_index=0,
        distance=0.20,
        parent_id="parent_1",
    )
    child_b = RetrievedChunk(
        chunk_id="c_b",
        text="child text b",
        source="doc1.pdf",
        page_number=1,
        chunk_index=1,
        distance=0.35,
        parent_id="parent_1",
    )
    child_c = RetrievedChunk(
        chunk_id="c_c",
        text="child text c",
        source="doc1.pdf",
        page_number=2,
        chunk_index=0,
        distance=0.15,
        parent_id="parent_2",
    )

    resolved = resolve_parent_context([child_a, child_b, child_c], parent_store=parent_store)
    # 3 children must collapse into exactly 2 parent contexts
    assert len(resolved) == 2
    assert resolved[0].chunk_id == "parent_1"
    assert resolved[1].chunk_id == "parent_2"
    assert resolved[0].text == "Full parent section 1 text spanning both child A and B."
    assert resolved[1].text == "Full parent section 2 text for child C."


def test_strongest_child_relevance_preserved_rerank_score():
    """8. When multiple children share a parent, the parent inherits the highest rerank_score."""
    parent_store = {
        "parent_X": {
            "parent_id": "parent_X",
            "text": "Parent section X.",
            "source": "doc.pdf",
            "page_number": 1,
        }
    }
    # Child 1 has lower rerank_score, Child 2 has higher rerank_score
    c1 = RetrievedChunk(
        chunk_id="c1",
        text="sub chunk 1",
        source="doc.pdf",
        page_number=1,
        chunk_index=0,
        distance=0.10,
        rerank_score=0.45,
        parent_id="parent_X",
    )
    c2 = RetrievedChunk(
        chunk_id="c2",
        text="sub chunk 2",
        source="doc.pdf",
        page_number=1,
        chunk_index=1,
        distance=0.20,
        rerank_score=0.92,
        parent_id="parent_X",
    )

    resolved = resolve_parent_context([c1, c2], parent_store=parent_store)
    assert len(resolved) == 1
    p = resolved[0]
    # Strongest child is c2 (rerank_score 0.92)
    assert p.rerank_score == 0.92
    assert p.original_child_id == "c2"


def test_strongest_child_relevance_preserved_distance():
    """9. When no rerank_score is present, lower distance (higher similarity) wins."""
    parent_store = {
        "parent_Y": {
            "parent_id": "parent_Y",
            "text": "Parent section Y.",
            "source": "doc.pdf",
            "page_number": 1,
        }
    }
    c_weak = RetrievedChunk(
        chunk_id="c_weak",
        text="weak chunk",
        source="doc.pdf",
        page_number=1,
        chunk_index=0,
        distance=0.40,
        parent_id="parent_Y",
    )
    c_strong = RetrievedChunk(
        chunk_id="c_strong",
        text="strong chunk",
        source="doc.pdf",
        page_number=1,
        chunk_index=1,
        distance=0.12,
        parent_id="parent_Y",
    )

    resolved = resolve_parent_context([c_weak, c_strong], parent_store=parent_store)
    assert len(resolved) == 1
    assert resolved[0].distance == 0.12
    assert resolved[0].original_child_id == "c_strong"


def test_document_id_and_source_preserved_on_parent():
    """10. Parent resolution correctly retains source, page_number, and document_id."""
    parent_store = {
        "parent_doc": {
            "parent_id": "parent_doc",
            "text": "Parent text content.",
            "source": "manual.pdf",
            "page_number": 5,
            "document_id": "sha256_manual_hash",
        }
    }
    child = RetrievedChunk(
        chunk_id="c_manual",
        text="child",
        source="manual.pdf",
        page_number=5,
        chunk_index=0,
        distance=0.18,
        document_id="sha256_manual_hash",
        parent_id="parent_doc",
    )

    resolved = resolve_parent_context([child], parent_store=parent_store)
    assert len(resolved) == 1
    p = resolved[0]
    assert p.source == "manual.pdf"
    assert p.page_number == 5
    assert p.document_id == "sha256_manual_hash"
    assert p.parent_id == "parent_doc"
    assert p.original_child_id == "c_manual"


def test_legacy_chunks_without_parent_id_fallback():
    """11. Legacy V1/V2 chunks without parent_id gracefully fallback to child text without crashing."""
    legacy_chunk = RetrievedChunk(
        chunk_id="legacy_p1_c0",
        text="Existing legacy chunk text from V1 index.",
        source="legacy.pdf",
        page_number=1,
        chunk_index=0,
        distance=0.25,
        parent_id=None,
    )
    resolved = resolve_parent_context([legacy_chunk], parent_store={})
    assert len(resolved) == 1
    assert resolved[0].chunk_id == "legacy_p1_c0"
    assert resolved[0].text == "Existing legacy chunk text from V1 index."
    assert resolved[0].original_child_id == "legacy_p1_c0"


def test_missing_parent_id_in_store_fallback():
    """12. If a child references a parent_id that does not exist in store, fallback to child."""
    child = RetrievedChunk(
        chunk_id="child_orphan",
        text="Orphan child text.",
        source="doc.pdf",
        page_number=2,
        chunk_index=0,
        distance=0.19,
        parent_id="nonexistent_parent_id",
    )
    resolved = resolve_parent_context([child], parent_store={})
    assert len(resolved) == 1
    assert resolved[0].chunk_id == "child_orphan"
    assert resolved[0].text == "Orphan child text."
    assert resolved[0].original_child_id == "child_orphan"


def test_empty_retrieved_list():
    """13. Empty candidate list returns empty list."""
    assert resolve_parent_context([]) == []
    assert resolve_parent_context([], parent_store={"any": "thing"}) == []


# ---------------------------------------------------------------------------
# Tests 14-22: Pipeline Integration, Reranking, Expansion, & Memory
# ---------------------------------------------------------------------------

def test_parent_child_disabled_preserves_old_behavior():
    """14. When parent_child_enabled=False, pipeline yields original child chunks unchanged."""
    child_chunk = RetrievedChunk(
        chunk_id="child_1",
        text="Child specific text.",
        source="report.pdf",
        page_number=1,
        chunk_index=0,
        distance=0.15,
        parent_id="parent_1",
    )
    parent_store = {
        "parent_1": {
            "parent_id": "parent_1",
            "text": "Expanded parent section text.",
            "source": "report.pdf",
            "page_number": 1,
        }
    }
    retriever = MockRetriever([child_chunk])
    generator = MockGenerator()
    pipeline = RAGPipeline(
        retriever=retriever,
        generator=generator,
        parent_store=parent_store,
        parent_child_enabled=False,
    )

    response = pipeline.ask("What is in report?", parent_child_enabled=False)
    assert response.parent_child_enabled is False
    assert len(response.retrieved_chunks) == 1
    # Must be the CHILD chunk text, not the parent text
    assert response.retrieved_chunks[0].text == "Child specific text."
    assert generator.last_retrieved_chunks[0].text == "Child specific text."


def test_parent_child_enabled_expands_to_parent_context():
    """15. When parent_child_enabled=True, pipeline expands context to full parent text."""
    child_chunk = RetrievedChunk(
        chunk_id="child_1",
        text="Child specific text.",
        source="report.pdf",
        page_number=1,
        chunk_index=0,
        distance=0.15,
        parent_id="parent_1",
    )
    parent_store = {
        "parent_1": {
            "parent_id": "parent_1",
            "text": "Expanded parent section text covering background.",
            "source": "report.pdf",
            "page_number": 1,
        }
    }
    retriever = MockRetriever([child_chunk])
    generator = MockGenerator()
    pipeline = RAGPipeline(
        retriever=retriever,
        generator=generator,
        parent_store=parent_store,
        parent_child_enabled=True,
    )

    response = pipeline.ask("What is in report?", parent_child_enabled=True)
    assert response.parent_child_enabled is True
    assert response.child_chunks_retrieved == 1
    assert response.parent_contexts_used == 1
    # Must be expanded PARENT text
    assert response.retrieved_chunks[0].text == "Expanded parent section text covering background."
    assert generator.last_retrieved_chunks[0].text == "Expanded parent section text covering background."


def test_pipeline_reranking_happens_before_parent_expansion():
    """16. Verification of exact pipeline order: children are reranked first, then parents resolved."""
    # Create two child chunks
    c1 = RetrievedChunk(
        chunk_id="c1",
        text="General irrelevant background mentioning fruit.",
        source="diet.pdf",
        page_number=1,
        chunk_index=0,
        distance=0.10,
        parent_id="parent_fruits",
    )
    c2 = RetrievedChunk(
        chunk_id="c2",
        text="Apples are rich in pectin and dietary fiber.",
        source="diet.pdf",
        page_number=2,
        chunk_index=0,
        distance=0.25,
        parent_id="parent_apples",
    )
    parent_store = {
        "parent_fruits": {
            "parent_id": "parent_fruits",
            "text": "Parent Fruits: Comprehensive overview of fruits.",
            "source": "diet.pdf",
            "page_number": 1,
        },
        "parent_apples": {
            "parent_id": "parent_apples",
            "text": "Parent Apples: Detailed study on apple varieties and nutrition.",
            "source": "diet.pdf",
            "page_number": 2,
        },
    }

    retriever = MockRetriever([c1, c2])
    generator = MockGenerator()
    reranker = TFIDFReranker()

    pipeline = RAGPipeline(
        retriever=retriever,
        generator=generator,
        reranker=reranker,
        parent_store=parent_store,
        parent_child_enabled=True,
    )

    # Query specifically about "pectin fiber apples"
    response = pipeline.ask("pectin fiber apples", top_k=1, parent_child_enabled=True)

    assert response.parent_child_enabled is True
    assert response.reranking_enabled is True
    # c2 had higher TF-IDF relevance to "pectin fiber apples", so c2 was selected as top-1 candidate
    # Parent context should be parent_apples, not parent_fruits!
    assert len(response.retrieved_chunks) == 1
    assert response.retrieved_chunks[0].chunk_id == "parent_apples"
    assert "Parent Apples:" in response.retrieved_chunks[0].text
    assert response.retrieved_chunks[0].original_child_id == "c2"


def test_pipeline_query_expansion_with_parent_child():
    """17. Query expansion produces candidate pool from multiple queries before parent resolution."""
    c1 = RetrievedChunk(
        chunk_id="c1",
        text="child 1",
        source="doc.pdf",
        page_number=1,
        chunk_index=0,
        distance=0.15,
        parent_id="p1",
    )
    parent_store = {
        "p1": {"parent_id": "p1", "text": "Parent 1 Text", "source": "doc.pdf", "page_number": 1}
    }

    mock_expander = MagicMock()
    mock_expander.expand.return_value = ["original query", "expanded query variation"]

    retriever = MockRetriever([c1])
    generator = MockGenerator()
    pipeline = RAGPipeline(
        retriever=retriever,
        generator=generator,
        query_expander=mock_expander,
        parent_store=parent_store,
        parent_child_enabled=True,
    )

    response = pipeline.ask("original query", parent_child_enabled=True)
    assert response.query_expansion_enabled is True
    assert len(response.expanded_queries) == 2
    assert response.parent_child_enabled is True
    assert response.retrieved_chunks[0].text == "Parent 1 Text"


def test_document_filtering_with_parent_child():
    """18. Document filtering restricts candidate retrieval before parent expansion."""
    c_doc1 = RetrievedChunk(
        chunk_id="c_d1",
        text="Doc 1 child text",
        source="doc1.pdf",
        page_number=1,
        chunk_index=0,
        distance=0.10,
        document_id="doc1",
        parent_id="p_d1",
    )
    c_doc2 = RetrievedChunk(
        chunk_id="c_d2",
        text="Doc 2 child text",
        source="doc2.pdf",
        page_number=1,
        chunk_index=0,
        distance=0.10,
        document_id="doc2",
        parent_id="p_d2",
    )
    parent_store = {
        "p_d1": {"parent_id": "p_d1", "text": "Doc 1 Parent", "source": "doc1.pdf", "page_number": 1},
        "p_d2": {"parent_id": "p_d2", "text": "Doc 2 Parent", "source": "doc2.pdf", "page_number": 1},
    }

    retriever = MockRetriever([c_doc1, c_doc2])
    generator = MockGenerator()
    pipeline = RAGPipeline(
        retriever=retriever,
        generator=generator,
        parent_store=parent_store,
        parent_child_enabled=True,
    )

    # Restrict to doc1 only
    response = pipeline.ask("query", document_ids=["doc1"], parent_child_enabled=True)
    assert len(response.retrieved_chunks) == 1
    assert response.retrieved_chunks[0].chunk_id == "p_d1"
    assert response.retrieved_chunks[0].text == "Doc 1 Parent"


def test_similarity_threshold_filtering_with_parent_child():
    """19. Similarity threshold filters low-relevance children before parent resolution."""
    c_high = RetrievedChunk(
        chunk_id="c_high",
        text="High match",
        source="doc.pdf",
        page_number=1,
        chunk_index=0,
        distance=0.20,  # similarity = 0.80
        parent_id="p_high",
    )
    c_low = RetrievedChunk(
        chunk_id="c_low",
        text="Low match",
        source="doc.pdf",
        page_number=2,
        chunk_index=0,
        distance=0.70,  # similarity = 0.30
        parent_id="p_low",
    )
    parent_store = {
        "p_high": {"parent_id": "p_high", "text": "High Parent", "source": "doc.pdf", "page_number": 1},
        "p_low": {"parent_id": "p_low", "text": "Low Parent", "source": "doc.pdf", "page_number": 2},
    }

    retriever = MockRetriever([c_high, c_low])
    generator = MockGenerator()
    pipeline = RAGPipeline(
        retriever=retriever,
        generator=generator,
        parent_store=parent_store,
        parent_child_enabled=True,
    )

    response = pipeline.ask("query", similarity_threshold=0.60, parent_child_enabled=True)
    assert len(response.retrieved_chunks) == 1
    assert response.retrieved_chunks[0].chunk_id == "p_high"
    assert response.retrieved_chunks[0].text == "High Parent"


def test_source_and_page_metadata_preserved_in_pipeline_sources():
    """20. Sources extracted by pipeline reflect parent section document and page."""
    c = RetrievedChunk(
        chunk_id="child_p3",
        text="child",
        source="guide.pdf",
        page_number=3,
        chunk_index=1,
        distance=0.15,
        parent_id="parent_p3",
    )
    parent_store = {
        "parent_p3": {"parent_id": "parent_p3", "text": "Parent text", "source": "guide.pdf", "page_number": 3}
    }
    retriever = MockRetriever([c])
    generator = MockGenerator()
    pipeline = RAGPipeline(
        retriever=retriever,
        generator=generator,
        parent_store=parent_store,
        parent_child_enabled=True,
    )

    response = pipeline.ask("How to install?", parent_child_enabled=True)
    assert len(response.sources) == 1
    assert response.sources[0]["source"] == "guide.pdf"
    assert response.sources[0]["page"] == 3


def test_conversation_memory_records_parent_child_metadata():
    """21. ChatMessage and Conversation store parent_child_enabled, child_chunks_retrieved, and parent_contexts_used."""
    conv = Conversation()
    msg = conv.add_assistant_message(
        content="Answer text",
        parent_child_enabled=True,
        child_chunks_retrieved=8,
        parent_contexts_used=3,
    )
    assert msg.parent_child_enabled is True
    assert msg.child_chunks_retrieved == 8
    assert msg.parent_contexts_used == 3


def test_mock_vector_store_parent_methods():
    """22. In-memory ParentChunk retrieval and lookup via vector_store-like duck typing."""
    class FakeVectorStore:
        def __init__(self):
            self.parents = {}

        def add_parents(self, parents):
            for p in parents:
                self.parents[p.parent_id] = p
            return len(parents)

        def get_parents(self, ids):
            return {pid: self.parents[pid] for pid in ids if pid in self.parents}

    store = FakeVectorStore()
    p_chunk = ParentChunk(
        parent_id="parent_99",
        text="Detailed parent text from fake vector store.",
        source="doc.pdf",
        page_number=1,
        parent_index=0,
    )
    store.add_parents([p_chunk])

    child = RetrievedChunk(
        chunk_id="c_99",
        text="small child",
        source="doc.pdf",
        page_number=1,
        chunk_index=0,
        distance=0.11,
        parent_id="parent_99",
    )
    resolved = resolve_parent_context([child], parent_store=store)
    assert len(resolved) == 1
    assert resolved[0].chunk_id == "parent_99"
    assert resolved[0].text == "Detailed parent text from fake vector store."


def test_hybrid_retrieval_with_parent_child():
    """23. Hybrid retrieval preserves parent_id through RRF fusion and resolves parent context."""
    # Semantic candidate
    c_sem = RetrievedChunk(
        chunk_id="child_sem",
        text="Semantic chunk text",
        source="tech.pdf",
        page_number=1,
        chunk_index=0,
        distance=0.15,
        semantic_rank=1,
        retrieval_method="semantic",
        parent_id="p_tech",
    )
    # BM25 candidate
    c_bm25 = RetrievedChunk(
        chunk_id="child_bm25",
        text="Keyword chunk text",
        source="tech.pdf",
        page_number=1,
        chunk_index=1,
        bm25_score=4.2,
        bm25_rank=1,
        retrieval_method="bm25",
        parent_id="p_tech",
    )
    parent_store = {
        "p_tech": {
            "parent_id": "p_tech",
            "text": "Full technology guide covering semantic and keyword topics.",
            "source": "tech.pdf",
            "page_number": 1,
        }
    }

    # Fuse both chunks
    fused_chunk = replace(
        c_sem,
        bm25_score=c_bm25.bm25_score,
        bm25_rank=c_bm25.bm25_rank,
        rrf_score=0.032,
        retrieval_method="hybrid",
    )

    resolved = resolve_parent_context([fused_chunk], parent_store=parent_store)
    assert len(resolved) == 1
    assert resolved[0].chunk_id == "p_tech"
    assert resolved[0].retrieval_method == "hybrid"
    assert resolved[0].rrf_score == 0.032
    assert resolved[0].original_child_id == "child_sem"


def test_chroma_vector_store_parent_crud(tmp_path):
    """24. ChromaVectorStore persists, retrieves, counts, and deletes parent records."""
    from app.vectorstore.chroma_store import ChromaVectorStore

    store = ChromaVectorStore(
        persist_dir=tmp_path / "chroma_test",
        collection_name="test_parent_collection",
        expected_dimension=4,
    )
    p1 = ParentChunk(
        parent_id="p_1",
        text="Parent text one",
        source="doc1.pdf",
        page_number=1,
        parent_index=0,
        document_id="doc1",
    )
    p2 = ParentChunk(
        parent_id="p_2",
        text="Parent text two",
        source="doc2.pdf",
        page_number=1,
        parent_index=0,
        document_id="doc2",
    )

    added = store.add_parents([p1, p2])
    assert added == 2
    assert store.count_parents() == 2

    # Fetch
    fetched = store.get_parents(["p_1", "p_2"])
    assert "p_1" in fetched and "p_2" in fetched
    assert fetched["p_1"]["text"] == "Parent text one"
    assert fetched["p_1"]["document_id"] == "doc1"

    # Delete by document_id
    store.delete_by_document_id("doc1")
    assert store.count_parents() == 1
    assert store.get_parent("p_1") is None
    assert store.get_parent("p_2") is not None

    # Reset
    store.reset()
    assert store.count_parents() == 0


def test_no_gemini_api_calls_in_tests():
    """25. Verification that RAG pipeline tests execute purely with local mocks without API calls."""
    child = RetrievedChunk(
        chunk_id="c_mock",
        text="local mocked chunk",
        source="mock.pdf",
        page_number=1,
        chunk_index=0,
        distance=0.1,
        parent_id="p_mock",
    )
    mock_retriever = MockRetriever([child])
    mock_generator = MockGenerator()
    pipeline = RAGPipeline(
        retriever=mock_retriever,
        generator=mock_generator,
        parent_store={"p_mock": {"parent_id": "p_mock", "text": "local parent text", "source": "mock.pdf", "page_number": 1}},
        parent_child_enabled=True,
    )
    resp = pipeline.ask("local question", parent_child_enabled=True)
    assert mock_generator.last_question == "local question"
    assert resp.answer.startswith("Grounded answer based on")
